export type Clientes = {
  bairro?: string;
  cep?: string;
  cgc?: string;
  cidade?: string;
  contrato?: string;
  email?: string;
  estado?: string;
  pais?: string;
  fantasia?: string;
  idcontador?: string;
  logradouro?: string;
  numero?: string;
  passsefaz?: string;
  plcontabil?: string;
  plfiscal?: string;
  plpessoal?: string;
  ramoatividade?: string;
  razaosocial?: string;
  telefone?: string;
  tipopessoa?: string;
  usursefaz?: string;
  cnae?: string;
};
